-- Скрипт для создания таблиц в базе данных

CREATE TABLE SavedDirectory (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    files_count INT DEFAULT 0,
    date_of_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dirs_count INT DEFAULT 0,
    files_size INT DEFAULT 0
);

CREATE TABLE HeaderFile (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    size DECIMAL DEFAULT NULL,
    dir_id INT,
    FOREIGN KEY (dir_id) REFERENCES SavedDirectory(id) ON DELETE CASCADE
);
